### ISSUE TITLE
use constraints with "tfupdate provider" to prevent major upgrades

### ISSUE THREAD

**Issue by rd-michel** [minamijoyo/tfupdate#106]
Hi,

ive got one questions (maybe its a feature request). is it possible to use constraints with "tfupdate provider".

example:
`tfupdate provider google --constraint="version<4.0.0"`

so that the terraform provider will be updated to latest 3.X.X version but not versions >=4.X.X. that would prevent an accidently upgrade to the next major version (e.g. 4.0.0)

**Comment by minamijoyo** [comment]
Hi @rd-michel, You can pass not only a version as a string literal but also a version constraint. (Duplicates #64)
https://developer.hashicorp.com/terraform/language/expressions/version-constraints

```
$ tfupdate provider google -v "~> 3.0" main.tf
```
