### ISSUE TITLE
Can't get lock to generate file

### ISSUE THREAD

**Issue by mattm-ecoatm** [minamijoyo/tfupdate#123]
Maybe I am misunderstanding on how to use lock, but I cannot get a lock file to generate.

This is what I have:

`versions.tf`
```
terraform {
  required_version = "~> 1.9"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.80.0"
    }
}
```

I basically run `tfupdate provider hashicorp/aws ./` and currently get that.

I then try to run `tfupdate lock --platform=linux_amd64 --platform=darwin_amd64 --platform=darwin_arm64 ./` and it seems like nothing is happening.

I guess I am not sure what I am missing, but I can't seem to get the lock file to generate. I have to use terraform to generate it still.

**Comment by minamijoyo** [comment]
The tfupdate doesn't create any files, but an empty file is enough to tell, so touch `.terraform.lock.hcl` should work.

**Comment by mattm-ecoatm** [comment]
ahhh ok, yes that worked. Thank you
