### ISSUE TITLE
FR: Gitlab integration

### ISSUE THREAD

**Issue by matsest** [minamijoyo/tfupdate#3]
Thank you for developing this! A much-needed tool when dealing with many terraform modules.

### Idea: gitlab.go equivalent of [release/github.go](https://github.com/minamijoyo/tfupdate/blob/master/release/github.go)

Would be very nice to have support for a [GitLab API client](https://github.com/xanzy/go-gitlab) to check for releases against GitLab as well. I guess an implementation should support to be able to set host and API-token to deal with hosted instances for projects that are not public on gitlab.com.

**Comment by matsest** [comment]
I have started a branch [here](https://github.com/matsest/tfupdate/tree/gitlab) where I have added a [gitlab.go](https://github.com/matsest/tfupdate/blob/gitlab/release/gitlab.go), but not sure how to design the command line flags/arguments to separate between github-releases and releases from GitLab.


I guess the safest is to read a token from a environmental variable, but not sure how to specify the hostname of the GitLab instance. This should maybe be specified in the CLI.

**Comment by minamijoyo** [comment]
@matsest Thank you for opening the issue. I'm not a Gitlab user, but a pull request is welcome.

As you mention, the current implementation implicitly assumes that release data source is only Github. I haven't decided on the interface design yet, so I will think while modifying the code what is the best fit here. If I add an interface for changing release data source, setting credential for private repo and changing hostname for testing to the existing GitHub, could you implement the Gitlab support referring to it?

**Comment by matsest** [comment]
Yes, sure that sounds like a good solution for this :) @minamijoyo

**Comment by minamijoyo** [comment]
OK, I'll refactor and fix the code related to release interface in my spare time.

**Comment by minamijoyo** [comment]
@matsest Done. Please check # 8 and # 9.

**Comment by matsest** [comment]
Thanks @minamijoyo - looks very promising! I'll see to it if I can use some time on it over the holidays.
