### ISSUE TITLE
Support shorter alias for terraform registry syntax

### ISSUE THREAD

**Issue by nitrocode** [minamijoyo/tfupdate#45]
This works

```
tfupdate release list cloudposse/kms-key/aws -s tfregistryModule
```

It's a lot more text than seems necessary. What do you think ? Could we do a `-t` so it's fewer chars ?

**Comment by minamijoyo** [comment]
@nitrocode Thank you for your proposal. I hesitate to add a new flag for alias because it limits future extensibility. If you feel it's too redundant, why not register a shell alias as you like?
