### ISSUE TITLE
Error: Cannot tap minamijoyo/tfupdate: invalid syntax in tap!

### ISSUE THREAD

**Issue by gretel** [minamijoyo/tfupdate#55]
```
$ brew --version
Homebrew 3.3.3
Homebrew/homebrew-core (git revision 0454127b489; last commit 2021-11-10)
Homebrew/homebrew-cask (git revision 0b85eec7ee; last commit 2021-11-10)

$ brew install minamijoyo/tfupdate/tfupdate
==> Tapping minamijoyo/tfupdate
Cloning into '/opt/homebrew/Library/Taps/minamijoyo/homebrew-tfupdate'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 69 (delta 21), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (69/69), 10.07 KiB | 10.07 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/minamijoyo/homebrew-tfupdate/tfupdate.rb
formulae require at least a URL
Error: Cannot tap minamijoyo/tfupdate: invalid syntax in tap!
Exception: brew exited with 1
```

**Comment by minamijoyo** [comment]
@gretel Thank you for reporting the issue! , but I cannot reproduce the error. 

> Error: Invalid formula: /opt/homebrew/Library/Taps/minamijoyo/homebrew-tfupdate/tfupdate.rb

Could you provide the formula file?

**Comment by minamijoyo** [comment]
I found a related issue in goreleaser https://github.com/goreleaser/goreleaser/issues/2389.
@gretel Do you use brew on M1 mac?

**Comment by gretel** [comment]
> I found a related issue in goreleaser [goreleaser/goreleaser#2389](https://github.com/goreleaser/goreleaser/issues/2389). @gretel Do you use brew on M1 mac?

yes, `m1` running `12.1`. the formula is the one from the `brew` repo.

**Comment by minamijoyo** [comment]
Thank you for reply. The syntax error looks strange, but I guess the root cause of the error seems that we don't have an arm64 build for m1 mac, so I'll add it a next release.

**Comment by minamijoyo** [comment]
Hi @gretel, I added arm64 builds in the latest v0.6.3 via #58. Could you retry it?

**Comment by gretel** [comment]
> Hi @gretel, I added arm64 builds in the latest v0.6.3 via #58. Could you retry it?

```
~> brew install minamijoyo/tfupdate/tfupdate
==> Downloading https://github.com/minamijoyo/tfupdate/releases/download/v0.6.3/tfupdate_0.6.3_darwin_arm64.tar.gz
Already downloaded: /Users/gretel/Library/Caches/Homebrew/downloads/0c28e0d490c6c53d1c1b9ecadd0d86116c1d080aa7c99b52a2b3f6d72af71607--tfupdate_0.6.3_darwin_arm64.tar.gz
==> Installing tfupdate from minamijoyo/tfupdate
🍺  /opt/homebrew/Cellar/tfupdate/0.6.3: 6 files, 11.9MB, built in 2 seconds
```

cool thanks!
