### ISSUE TITLE
Support .terraform.lock.hcl files when upgrading providers

### ISSUE THREAD

**Issue by jrobison-sb** [minamijoyo/tfupdate#68]
Terraform 0.14 and higher uses `.terraform.lock.hcl` files with a hash of each provider/platform to be used. It would be nice if tfupdate was able to auto-update these lock files when upgrading providers. For example:

```
tfupdate --version 1.2.3 --recursive --platform darwin_amd64 --platform linux_amd64 aws ./
```

And this would do what tfupdate already does, and it would also do the equivalent of `terraform providers lock -platform=darwin_amd64 -platform=linux_amd64` and recursively update all the lockfiles.

**Comment by minamijoyo** [comment]
The tfupdate v0.7.0 introduced a new tfupdate lock command. For details, see https://github.com/minamijoyo/tfupdate/pull/90
